# Generated by Django 5.1.3 on 2026-02-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="noticias/"),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
