# Generated by Django 5.2.11 on 2026-02-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_categoria_slug_alter_noticia_imagem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("x", "X (Twitter)"),
                            ("facebook", "Facebook"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="Link")),
                (
                    "is_visible",
                    models.BooleanField(default=False, verbose_name="Visível no topo"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
            ],
            options={
                "verbose_name": "Rede social",
                "verbose_name_plural": "Redes sociais",
                "ordering": ["order", "platform"],
            },
        ),
    ]
