# Generated by Django 5.1.3 on 2026-02-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sociallink"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "ordering": ["order", "nome"],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.AddField(
            model_name="categoria",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordem"),
        ),
    ]
