# Generated by Django 5.1.3 on 2026-02-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_categoria_options_categoria_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="publicado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="resumo",
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddIndex(
            model_name="noticia",
            index=models.Index(
                fields=["publicado", "-publicado_em"],
                name="core_notici_publica_258780_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="noticia",
            index=models.Index(fields=["slug"], name="core_notici_slug_699d2f_idx"),
        ),
    ]
