# Generated by Django 5.1.3 on 2026-02-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_noticia_publicado_alter_noticia_resumo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="destaque",
            field=models.BooleanField(default=False, verbose_name="Destacar na capa"),
        ),
        migrations.AddIndex(
            model_name="noticia",
            index=models.Index(
                fields=["destaque", "publicado", "-publicado_em"],
                name="core_notici_destaqu_7119c9_idx",
            ),
        ),
    ]
