# Generated by Django 5.1.3 on 2026-02-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_noticia_destaque_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="noticia",
            name="core_notici_destaqu_7119c9_idx",
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="destaque",
        ),
        migrations.AddField(
            model_name="noticia",
            name="destaque_principal",
            field=models.BooleanField(default=False, verbose_name="Destaque principal"),
        ),
        migrations.AddField(
            model_name="noticia",
            name="destaque_secundario",
            field=models.BooleanField(
                default=False, verbose_name="Destaque secundário"
            ),
        ),
        migrations.AddField(
            model_name="noticia",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Visualizações"
            ),
        ),
        migrations.AddIndex(
            model_name="noticia",
            index=models.Index(
                fields=["destaque_principal", "publicado", "-publicado_em"],
                name="core_notici_destaqu_676956_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="noticia",
            index=models.Index(
                fields=["destaque_secundario", "publicado", "-publicado_em"],
                name="core_notici_destaqu_ed9901_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="noticia",
            index=models.Index(
                fields=["views_count"], name="core_notici_views_c_f3294d_idx"
            ),
        ),
    ]
