# Generated by Django 5.1.3 on 2026-02-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_noticia_core_notici_destaqu_7119c9_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_name",
                    models.CharField(
                        default="Kero Agro",
                        max_length=80,
                        verbose_name="Nome do portal",
                    ),
                ),
                (
                    "about_tagline",
                    models.CharField(
                        blank=True,
                        default="Portal de notícias do agro e sertanejo",
                        max_length=120,
                        verbose_name="Slogan/descrição curta",
                    ),
                ),
                (
                    "about_text",
                    models.TextField(
                        blank=True,
                        default="O Kero Agro é um portal de conteúdo sobre agricultura, pecuária, agronegócio e cultura sertaneja. Informação com linguagem simples, visual limpo e foco no que importa no campo.",
                        verbose_name="Texto principal (Sobre o portal)",
                    ),
                ),
                (
                    "about_text_muted",
                    models.TextField(
                        blank=True,
                        default="Produzimos conteúdo com responsabilidade e independência editorial.",
                        verbose_name="Texto secundário (linha menor)",
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        blank=True,
                        default="© 2026 Kero Agro — Portal de notícias do agro.",
                        max_length=140,
                        verbose_name="Texto de copyright",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração do portal",
                "verbose_name_plural": "Configurações do portal",
            },
        ),
    ]
